[default_apps]
teams = "teams-for-linux --enable-features=UseOzonePlatform --ozone-platform=wayland --url {meeting_url}"
calendar_client = "thunderbird"
terminal = "ghostty"
browser = "chromium %U"

[units]
lengths = "meters"
weights = "kg"
volumes = "l"
temperatures = "C"
_currency = "cad"

[debug]
try_suppress_errors = false
try_suppress_warnings = false
app_paths = []

[appearance]
width = 900
height = 593
gsk_renderer = "cairo"
icon_paths = ["~/.config/sherlock/p'picons/"]
icon_size = 22
search_icon = false
use_base_css = true
status_bar = true
opacity = 1.0
mod_key_ascii = ["⇧", "⇧", "⌘", "⌘", "⎇", "✦", "✦", "⌘"]

[behavior]
cache = "~/.cache/sherlock/sherlock_desktop_cache.json"
caching = false
daemonize = false
animate = true

[binds]

[files]
config = "~/.config/sherlock/config.toml"
css = "~/.config/sherlock/main.css"
fallback = "~/.config/sherlock/fallback.json"
alias = "~/.config/sherlock/sherlock_alias.json"
ignore = "~/.config/sherlock/sherlockignore"
actions = "~/.config/sherlock/sherlock_actions.json"

[pipe]
