-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(ff6d00)",
			inactive_border = "rgb(a08d85)",
		},
	},
	group = {
		col = {
			border_active = "rgb(ff6d00)",
			border_inactive = "rgb(a08d85)",
			border_locked_active = "rgb(f2b8b5)",
			border_locked_inactive = "rgb(a08d85)",
		},
		groupbar = {
			col = {
				active = "rgb(ff6d00)",
				inactive = "rgb(a08d85)",
				locked_active = "rgb(f2b8b5)",
				locked_inactive = "rgb(a08d85)",
			},
		},
	},
})
