# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "pata_atiixp" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.loader.grub = {
    enable  = true;
    device  = "/dev/sdg";   # install GRUB to MBR
    efiSupport = false;
  };
  boot.loader.efi.canTouchEfiVariables = false;


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d8cbcc6d-a61c-411e-9d1c-dca986261d86";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/ae5fd844-bee4-4694-90eb-19591589eaad";
      fsType = "ext4";
    };

  fileSystems."/nix/store" =
    { device = "/dev/disk/by-uuid/31eb6380-6c3a-4f79-a13c-8ccc4e775fe7";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/249085eb-f465-4075-8e26-c61a5993d3bf";
      fsType = "btrfs";
    };

  fileSystems."/data/fourTerra" =
    { device = "/dev/sde1";
      fsType = "btrfs";
    };

  fileSystems."/data/twoHundoGigs" =
    { device = "/dev/disk/by-uuid/fb6f1634-c0cc-440f-8fbf-1b655b39245a";
      fsType = "btrfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
