#!/bin/bash

set -e

name=${1:-new}
dep=${2:-stag}

cmd="helm template --values test_values.yaml --values values.yaml --values values-$dep.yaml"

if [ ! -z "values-$dep.auto.yaml"]; then
    cmd="$cmd --values values-$dep.auto.yaml"
fi

cmd="$cmd --debug . > tmp/$name.yml"
echo $cmd

$cmd

if [ $name == "new" ];

    if [ ! -z "tmp/old.yml" ]; then
        diff tmp/original.yml tmp/new.yml > tmp/diff
    fi

fi