
live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/nord.toml"
]

[window]
title = "Terminal"
blur = true

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }

[shell]
program = "/home/ari/.nix-profile/bin/zsh"
args = [
	"-l",
	"-c",
	"tmux attach || tmux"
]	

